---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kingbain/g.statuslights.dev
    - /bin/mkdir -p $DEPLOYPATH/cache
    - /bin/cp generator/index.php $DEPLOYPATH/index.php
    - /bin/chmod 0755 $DEPLOYPATH/cache
